
# A typical Rakefile

PORT  = 6238 # momo was here
HOSTS = hostname1 hostname2 hostname3:6333

		
actionset1:
	./test_command 
	remote-./test_command 3
	remote-cal
	echo hello world
	mkdir hello
	cc
	
actionset2:
	remote-rmdir hello
	cal jjjjjjjjjjjjjjjjj
